theme: jekyll-theme-minimal

title: Valeria Niño Albornoz
description: >
  Bienvenido a mi portafolio de proyectos de análisis de datos

logo:/IMG_1804.jpeg

github:
  is_user_page: true
  is_project_page: false
